<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>GutsV</AssemblyName>
    <Product>GutsV Colour</Product>
    <Title>GutsV Colour</Title>
    <Authors>acerhizm</Authors>
    <ApplicationIcon>icon.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.3.2" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="icon.png" />
    <None Update="icon.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GutsV.Core\GutsV.Core.csproj" />
    <ProjectReference Include="..\GutsV.Drivers\GutsV.Drivers.csproj" />
  </ItemGroup>





</Project>
